[package]
edition = "2021"
name = "gu-currency"
version = "4.0.0-dev"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
codec = {package = "parity-scale-codec", version = "3.0.0", default-features = false, features = [
  "derive",
]}
rustc-hex = {version = "2.1.0", default-features = false}
scale-info = {version = "2.1.0", default-features = false, features = ["derive"]}
serde = {version = "1.0.119"}
sha3 = {version = "0.10", default-features = false}

# Substrate
frame-support = {default-features = false, version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.23"}
frame-system = {default-features = false, version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.23"}
sp-core = {default-features = false, version = "6.0.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.23"}
sp-io = {default-features = false, version = "6.0.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.23"}
sp-runtime = {default-features = false, version = "6.0.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.23"}
sp-std = {default-features = false, version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.23"}
pallet-balances = {default-features = false, version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.23"}

# Local
gafi-primitives = {default-features = false, version = "4.0.0-dev", path = "../../primitives"}

[dev-dependencies]
hex-literal = "0.2.1"
parity-secp256k1 = {default-features = false, version = "0.7.0", git = "https://github.com/cryptoviet/rust-secp256k1"}

[features]
default = ["std"]
std = [
  "sp-runtime/std",
  "sp-io/std",
  "sp-core/std",
  "sha3/std",
  "scale-info/std",
  "codec/std",
  "serde/std",
  "rustc-hex/std",
  "sp-std/std",
  "frame-system/std",
  "frame-support/std",
  "gafi-primitives/std",
  "pallet-balances/std",
]
