[package]
authors = ["Substrate DevHub <https://github.com/substrate-developer-hub>"]
build = "build.rs"
description = "A fresh FRAME-based Substrate node, ready for hacking."
edition = "2021"
homepage = "https://substrate.io/"
license = "Unlicense"
name = "gafi-node"
publish = false
repository = "https://github.com/substrate-developer-hub/substrate-node-template/"
version = "4.0.0-dev"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[[bin]]
name = "gafi-node"

[dependencies]

# Frontier
fc-rpc = { workspace = true}
pallet-ethereum = {git = "https://github.com/grindytech/frontier", branch = "gafi-polkadot-v0.9.37"}

# Substrate
sc-cli = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.37"}
sc-consensus-aura = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.37", optional = true}
sc-consensus-manual-seal = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.37", optional = true}

# Local
gafi-cli = {path = "cli", default-features = false, optional = true}
gafi-local = {path = "local", default-features = false, optional = true}
gafi-service = {path = "service", default-features = false, optional = true}

[build-dependencies]
substrate-build-script-utils = {git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.37"}

[features]
aura = [
  "sc-consensus-aura",
  "gafi-local/aura",
]
default = ["aura", "with-dev"]

std = []

manual-seal = [
  "sc-consensus-manual-seal",
  "gafi-local/manual-seal",
]
# rpc_binary_search_estimate = ["fc-rpc/rpc_binary_search_estimate"]
# runtime-benchmarks = [
#   "gafi-cli/runtime-benchmarks",
#   "with-gari",
# ]

runtime-benchmarks = [
  "gafi-local/runtime-benchmarks",
  "aura",
]

with-dev = [
  "gafi-local/with-dev",
  "gafi-local/aura",
]

with-gari = [
  "gafi-cli/with-gari",
  "gafi-service/with-gari",
]

rococo-native = [
	"gafi-service/rococo-native"
]
